#!/bin/sh

set -e

GIT_USER=$(git config user.name)
GIT_EMAIL=$(git config user.email)
COMMIT_MSG_FILE=$1

touch -a $COMMIT_MSG_FILE
mkdir -p web/.git
cp $COMMIT_MSG_FILE web/.git/COMMIT_EDITMSG

# Fetch the GIT diff and format it as command input:

cd "web"
DIFF=$(git -c diff.mnemonicprefix=false -c diff.noprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged | cat)

# Grumphp env vars
export GRUMPHP_GIT_WORKING_DIR="$(git rev-parse --show-toplevel)"

# Run GrumPHP
(cd ".." && printf "%s\n" "${DIFF}" | docker-compose run --rm --no-deps -T php-fpm php 'vendor/bin/grumphp' 'git:commit-msg' "--git-user='$GIT_USER'" "--git-email='$GIT_EMAIL'" "$COMMIT_MSG_FILE")

cd ".." && rm web/.git -R
